### PR TITLE
PSX: Beetle as experimental core for aarch64, with dynarec enabled.

### PR DESCRIPTION
**Pull request by dankcushions**
On ARM the dynarec can crash/lock in many games. On aarch64 it seems to be fullspeed in some games, dropping frame in others, but stable from my brief tests.

### CODE REVIEW

**Comment by dankcushions** [comment]
Please take a look at this one as I think it's good to go :)

**Comment by joolswills** [comment]
Thanks. Will merge but will keep it in optional. My branch is not ready to be tracked so you will.need to reset your local still for now. I need to test the mupen64plus changes on Mali. Also it will need reviewing when I do a PR against master.

But feel free to submit PRs now against my branch here.

**Comment by joolswills** [comment]
Actually. I'm going to push my branch to the main repo so might be better to wait. At that point I'll stop rebasing but if accepting PRs here, merge commits are not going to be that useful and I want to avoid references to another repo.

**Comment by joolswills** [comment]
I cherry picked with some changes and committed to my branch. Thanks.

**Pull request closed without merging**
